import AppKit
import os
import XCTest

@testable import portavoz_app

@MainActor
final class DictationClipboardInsertionTests: XCTestCase {
    func testInsertionRestoresEveryItemAndRepresentationInOrder() async throws {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        let values = ["Don't delete — café", "No borres 1.250,50 €"]
        let items = values.map { text in
            let item = NSPasteboardItem()
            item.setString(text, forType: .string)
            item.setData(Data("<p>\(text)</p>".utf8), forType: .html)
            return item
        }
        XCTAssertTrue(board.writeObjects(items))
        let before = contents(board)
        var sent: String?
        let result = await insert("Own text", on: board) { sent = board.string(forType: .string); return true }
        XCTAssertEqual(result, .inserted)
        XCTAssertEqual(sent, "Own text")
        try await Task.sleep(for: TextInserter.restoreDelay + .milliseconds(100))
        XCTAssertEqual(contents(board), before)
    }

    func testUnknownRepresentationNeverInvokesProviderOrPosts() async {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        let unknown = NSPasteboard.PasteboardType("app.portavoz.tests.unbounded-provider")
        let provider = ClipboardInsertionProvider(data: Data([1]))
        let item = NSPasteboardItem()
        item.setString("Keep original", forType: .string)
        item.setDataProvider(provider, forTypes: [unknown])
        XCTAssertTrue(board.writeObjects([item]))
        let generation = board.changeCount
        var posts = 0
        let result = await insert("No conversion", on: board) { posts += 1; return false }
        XCTAssertEqual(result, .clipboardUnavailable)
        XCTAssertEqual(posts, 0)
        XCTAssertEqual(provider.reads, 0)
        XCTAssertEqual(board.changeCount, generation)
    }

    func testUnreadableRichFormatCannotBecomeSuccessfulPlainTextSnapshot() async {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        let provider = ClipboardInsertionProvider(data: nil)
        let item = NSPasteboardItem()
        item.setString("Keep every format", forType: .string)
        item.setDataProvider(provider, forTypes: [.rtf])
        board.writeObjects([item])
        let generation = board.changeCount
        var posts = 0
        let result = await insert("Refuse partial preservation", on: board) { posts += 1; return false }
        XCTAssertEqual(result, .clipboardUnavailable)
        XCTAssertEqual(posts, 0)
        XCTAssertEqual(board.changeCount, generation)
    }

    func testSecondPasteWaitsUntilFirstDeferredReaderFinished() async throws {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        board.setString("Original", forType: .string)
        var reader: Task<String?, Never>?
        let first = await insert("First — primero", on: board) {
            reader = Task {
                try? await Task.sleep(for: .milliseconds(100))
                return board.string(forType: .string)
            }
            return true
        }
        XCTAssertEqual(first, .inserted)
        let second = await insert("Second — segundo", on: board) { true }
        XCTAssertEqual(second, .inserted)
        let observed = await reader?.value
        XCTAssertEqual(observed, "First — primero", "Restoring later does not repair a paste that read the wrong dictation")
        try await Task.sleep(for: TextInserter.restoreDelay + .milliseconds(100))
        XCTAssertEqual(board.string(forType: .string), "Original")
    }

    func testForeignSameTextWriteSurvivesDelayedRestoration() async throws {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        board.setString("Prior owner", forType: .string)
        let result = await insert("Identical content", on: board) { true }
        XCTAssertEqual(result, .inserted)
        board.clearContents()
        board.setString("Identical content", forType: .string)
        let foreignGeneration = board.changeCount
        try await Task.sleep(for: TextInserter.restoreDelay + .milliseconds(100))
        XCTAssertEqual(board.changeCount, foreignGeneration)
        XCTAssertEqual(board.string(forType: .string), "Identical content")
    }

    func testPrivacyMarkersExistAtActualPostAndFailedPostRestoresEmptyBoard() async {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        var calls = 0
        let result = await insert("Private dictation", on: board) {
            calls += 1
            let types = Set(board.types?.map(\.rawValue) ?? [])
            for marker in ["TransientType", "ConcealedType", "AutoGeneratedType"] {
                XCTAssertTrue(types.contains("org.nspasteboard." + marker))
            }
            return false
        }
        XCTAssertEqual(result, .eventUnavailable)
        XCTAssertEqual(calls, 1)
        XCTAssertTrue(board.pasteboardItems?.isEmpty != false)
    }

    func testCancellationDuringLazyReadDoesNotBorrowOrPost() async {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        let taskBox = OSAllocatedUnfairLock<Task<TextInserter.InsertionResult, Never>?>(initialState: nil)
        let provider = ClipboardInsertionProvider(data: Data([1]), onRead: { taskBox.withLock { $0?.cancel() } })
        let item = NSPasteboardItem()
        item.setDataProvider(provider, forTypes: [.init("org.nspasteboard.source")])
        board.writeObjects([item])
        let generation = board.changeCount
        var posts = 0
        let task = Task { await insert("Cancelled", on: board) { posts += 1; return false } }
        taskBox.withLock { $0 = task }
        let result = await task.value
        taskBox.withLock { $0 = nil }
        XCTAssertEqual(provider.reads, 1)
        XCTAssertEqual(result, .cancelled)
        XCTAssertEqual(posts, 0)
        XCTAssertEqual(board.changeCount, generation)
    }

    func testSecureFieldAppearingDuringProviderReadPreventsDispatch() async {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        let becameSecure = OSAllocatedUnfairLock(initialState: false)
        let provider = ClipboardInsertionProvider(data: Data([1]), onRead: { becameSecure.withLock { $0 = true } })
        let item = NSPasteboardItem()
        item.setDataProvider(provider, forTypes: [.init("org.nspasteboard.source")])
        board.writeObjects([item])
        var posts = 0
        let result = await TextInserter.insert(
            "Not a password", pasteboard: board, eventTarget: testTarget,
            effects: .init(isTargetAvailable: { _ in true }, waitForModifiers: { true }, focusedSecurity: { _ in
                becameSecure.withLock { $0 } ? .secure : .regular
            }, post: { _ in posts += 1; return false }))
        XCTAssertEqual(result, .secureField)
        XCTAssertEqual(posts, 0)
        XCTAssertEqual(board.pasteboardItems?.first?.data(forType: .init("org.nspasteboard.source")), Data([1]))
    }

    func testForeignWriteDuringFinalFieldInspectionCannotBePostedOrRestoredOver() async {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        board.setString("Original", forType: .string)
        var inspections = 0
        var posts = 0
        let result = await TextInserter.insert(
            "Own text", pasteboard: board, eventTarget: testTarget,
            effects: .init(isTargetAvailable: { _ in true }, waitForModifiers: { true }, focusedSecurity: { _ in
                inspections += 1
                if inspections == 2 {
                    board.clearContents()
                    board.setString("Foreign copy", forType: .string)
                }
                return .regular
            }, post: { _ in posts += 1; return false }))
        XCTAssertEqual(result, .clipboardUnavailable)
        XCTAssertEqual(posts, 0)
        XCTAssertEqual(board.string(forType: .string), "Foreign copy")
    }

    func testProcessTargetIsUsedForBothSecurityChecksAndDispatch() async {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        board.setString("Preserve", forType: .string)
        var inspected: [pid_t] = []
        var posted: pid_t?
        let result = await TextInserter.insert("No borres", pasteboard: board, eventTarget: testTarget,
            effects: .init(isTargetAvailable: { _ in true }, waitForModifiers: { true }, focusedSecurity: { target in
                guard case .process(let processID) = target else {
                    XCTFail("Clipboard admission must not inspect system-wide focus")
                    return .unavailable
                }
                inspected.append(processID)
                return .regular
            }, post: { target in
                guard case .process(let processID) = target else {
                    XCTFail("Clipboard delivery must not fall back to session routing")
                    return false
                }
                posted = processID
                return false
            }))
        let ownPID = ProcessInfo.processInfo.processIdentifier
        XCTAssertEqual(result, .eventUnavailable)
        XCTAssertEqual(inspected, [ownPID, ownPID])
        XCTAssertEqual(posted, ownPID)
        XCTAssertEqual(board.string(forType: .string), "Preserve")
    }

    func testTargetLostDuringLazyReadRestoresWithoutPosting() async {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        let available = OSAllocatedUnfairLock(initialState: true)
        let provider = ClipboardInsertionProvider(data: Data([1]), onRead: {
            available.withLock { $0 = false }
        })
        let item = NSPasteboardItem()
        item.setDataProvider(provider, forTypes: [.init("org.nspasteboard.source")])
        XCTAssertTrue(board.writeObjects([item]))
        var posts = 0
        let result = await TextInserter.insert("Never paste", pasteboard: board, eventTarget: testTarget,
            effects: .init(isTargetAvailable: { _ in available.withLock { $0 } },
                           waitForModifiers: { true }, focusedSecurity: { _ in .regular },
                           post: { _ in posts += 1; return true }))
        XCTAssertEqual(provider.reads, 1)
        XCTAssertEqual(result, .eventUnavailable)
        XCTAssertEqual(posts, 0)
        XCTAssertEqual(board.pasteboardItems?.first?.data(forType: .init("org.nspasteboard.source")), Data([1]))
    }

    func testSecondArrivalDuringModifierWaitCannotStealExclusiveLoan() async throws {
        let board = makeBoard()
        defer { board.releaseGlobally() }
        board.setString("Original", forType: .string)
        var posts = 0
        let result = await TextInserter.insert(
            "Late contender", pasteboard: board, eventTarget: testTarget,
            effects: .init(isTargetAvailable: { _ in true }, waitForModifiers: {
                let first = await self.insert("First posted", on: board) { posts += 1; return true }
                XCTAssertEqual(first, .inserted)
                return true
            }, focusedSecurity: { _ in .regular }, post: { _ in posts += 1; return true }))
        XCTAssertEqual(result, .clipboardUnavailable)
        XCTAssertEqual(posts, 1)
        XCTAssertEqual(board.string(forType: .string), "First posted")
        try await Task.sleep(for: TextInserter.restoreDelay + .milliseconds(100))
        XCTAssertEqual(board.string(forType: .string), "Original")
    }

    private func insert(
        _ text: String, on board: NSPasteboard, post: @escaping @MainActor () -> Bool
    ) async -> TextInserter.InsertionResult {
        await TextInserter.insert(text, pasteboard: board, eventTarget: testTarget,
            effects: .init(isTargetAvailable: { _ in true }, waitForModifiers: { true },
                           focusedSecurity: { _ in .regular }, post: { _ in post() }))
    }

    private var testTarget: TextInserter.EventTarget {
        .process(ProcessInfo.processInfo.processIdentifier)
    }

    private func makeBoard() -> NSPasteboard {
        let board = NSPasteboard(name: .init("app.portavoz.clipboard-test.\(UUID().uuidString)"))
        board.clearContents()
        return board
    }

    private func contents(_ board: NSPasteboard) -> [[String: Data]] {
        (board.pasteboardItems ?? []).map { item in
            Dictionary(uniqueKeysWithValues: item.types.compactMap { type in
                item.data(forType: type).map { (type.rawValue, $0) }
            })
        }
    }
}

private final class ClipboardInsertionProvider: NSObject, NSPasteboardItemDataProvider {
    let data: Data?
    let onRead: (@Sendable () -> Void)?
    private let count = OSAllocatedUnfairLock(initialState: 0)
    var reads: Int { count.withLock { $0 } }

    init(data: Data?, onRead: (@Sendable () -> Void)? = nil) {
        self.data = data
        self.onRead = onRead
    }

    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem,
                    provideDataForType type: NSPasteboard.PasteboardType) {
        count.withLock { $0 += 1 }
        onRead?()
        if let data { item.setData(data, forType: type) }
    }
}
