import AppKit
import os

/// One owner per board serializes clipboard borrowing. Only a matching loan
/// may restore; a foreign write retires it without overwriting the new owner.
@MainActor
final class DictationClipboard {
    static let shared = DictationClipboard()
    private static let logger = Logger(subsystem: "app.portavoz.mac", category: "dictation-clipboard")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let generated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    /// Grace after a scheduled restoration before a waiter performs it itself.
    private static let restorationMargin: Duration = .seconds(2)

    struct Loan: Equatable {
        fileprivate let name: NSPasteboard.Name
        fileprivate let id: UUID
        fileprivate let changeCount: Int
    }

    private struct State {
        let loan: Loan
        let original: PasteboardSnapshot
        /// The scheduled restore and when a waiter may stop trusting it.
        var restoration: (task: Task<Void, Never>, deadline: ContinuousClock.Instant)?
    }

    private var states: [NSPasteboard.Name: State] = [:]
    private var isMutating = false
    var pendingLoanCount: Int { states.count }

    /// A posted event may not have read the clipboard yet. Do not replace it
    /// for another dictation until its existing restoration window has ended.
    /// The wait is bounded: a restoration that could not run within its own
    /// window plus a margin is performed now, still only while the loan owns
    /// the board, and the loan is retired, so dictation can never hang behind
    /// it and the user's original clipboard is not left replaced.
    func waitForRestoration(on pasteboard: NSPasteboard) async -> Bool {
        while let state = states[pasteboard.name], let restoration = state.restoration {
            guard ContinuousClock.now < restoration.deadline else {
                Self.logger.error("Clipboard restoration missed its window; restoring before retiring the loan.")
                restore(state.loan, on: pasteboard)
                retire(pasteboard.name)
                break
            }
            do { try await Task.sleep(for: .milliseconds(25)) } catch { return false }
        }
        return !Task.isCancelled
    }

    func borrow(_ text: String, on pasteboard: NSPasteboard) -> Loan? {
        guard !isMutating, !text.isEmpty, states[pasteboard.name] == nil,
              let item = Self.item(text) else { return nil }
        isMutating = true
        defer { isMutating = false }
        guard let original = PasteboardSnapshot(of: pasteboard),
              pasteboard.changeCount == original.changeCount, !Task.isCancelled else { return nil }
        let generation = pasteboard.prepareForNewContents(with: .currentHostOnly)
        let loan = Loan(name: pasteboard.name, id: UUID(), changeCount: generation)
        states[pasteboard.name] = State(loan: loan, original: original)
        guard pasteboard.writeObjects([item]), isCurrent(loan, on: pasteboard) else {
            restoreOwned(loan, on: pasteboard)
            return nil
        }
        return loan
    }

    func isCurrent(_ loan: Loan, on pasteboard: NSPasteboard) -> Bool {
        loan.name == pasteboard.name && states[loan.name]?.loan == loan
            && pasteboard.changeCount == loan.changeCount
    }

    func restore(_ loan: Loan, on pasteboard: NSPasteboard) {
        guard !isMutating else { return }
        isMutating = true
        defer { isMutating = false }
        restoreOwned(loan, on: pasteboard)
    }

    func restoreLater(_ loan: Loan, on pasteboard: NSPasteboard, after delay: Duration) {
        guard loan.name == pasteboard.name, states[loan.name]?.loan == loan,
              states[loan.name]?.restoration == nil else { return }
        // Strong capture: a released owner must not silently strand the
        // borrowed text. Retiring the loan cancels this bounded task.
        let task = Task {
            do { try await Task.sleep(for: delay) } catch { return }
            // Never skip a deferred restore because another synchronous
            // mutation is in progress: yield until it ends, then restore.
            while self.isMutating {
                do { try await Task.sleep(for: .milliseconds(10)) } catch { return }
            }
            self.restore(loan, on: pasteboard)
        }
        states[loan.name]?.restoration = (task, ContinuousClock.now.advanced(by: delay + Self.restorationMargin))
    }

    private func restoreOwned(_ loan: Loan, on pasteboard: NSPasteboard) {
        guard loan.name == pasteboard.name, let state = states[loan.name], state.loan == loan else { return }
        let owned = isCurrent(loan, on: pasteboard)
        retire(loan.name)
        guard owned else { return }
        // A board-server failure cannot authorize overwriting a later owner.
        // Restoration never repeats an editor event or stores the old bytes.
        if !state.original.restore(to: pasteboard, expectedChangeCount: loan.changeCount) {
            Self.logger.error("Clipboard restoration failed or ownership changed; no retry was performed.")
        }
    }

    private func retire(_ name: NSPasteboard.Name) {
        states.removeValue(forKey: name)?.restoration?.task.cancel()
    }

    private static func item(_ text: String) -> NSPasteboardItem? {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string), item.setData(Data(), forType: concealed) else { return nil }
        guard item.setData(Data(), forType: Self.transient),
              item.setData(Data(), forType: generated) else { return nil }
        return item
    }
}
